image: registry.hypriot.com/armbuildchain/dockerindocker
docker:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
git:
  path: github.com/hypriot/cluster-lab
script:
  - echo "+++++ start docker daemon +++++"
  - wrapdocker &
  - sleep 5
  - docker login --username=$$REGISTRY_USER --password=$$REGISTRY_PASSWORD --email=$$REGISTRY_USER_EMAIL $$REGISTRY_URL
  - echo "+++++ build docker image +++++"
  - make
  - echo "+++++ stop docker daemon +++++"
  - start-stop-daemon --stop --pidfile "/var/run/docker.pid"
  - echo -e "#####################\n***** COMPLETED *****\n#####################"
publish:
  s3:
    acl: public-read
    region: $$AWS_DEFAULT_REGION
    bucket: $$AWS_BUCKET
    access_key: $$AWS_ACCESS_KEY_ID
    secret_key: $$AWS_SECRET_ACCESS_KEY
    source: $$BUILD_RESULTS
    target: $$S3_PREFIX
    recursive: true
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    on_started: false
    on_success: true
    on_failure: true

