#!/usr/bin/env bash

declare DOCKER_INFO

function docker_info(){
  if [[ -z "${DOCKER_INFO}" ]]; then
    DOCKER_INFO=$(docker info)
  fi
  echo "$DOCKER_INFO"
}

function pre_check_docker(){
  echo -e "\nDocker"
  ERRORS=0

  # instead of checking different package name variants
  # we check for the existence of the docker cli command
  command -v docker > /dev/null 2>&1
  evaluate_result $? "  docker is installed"

  check_if_process_exists "docker"
  evaluate_result $? "  Docker process exists"

  [[ (! -f "/etc/default/docker.cluster-lab-backup") ]]
  evaluate_result $? "  /etc/default/docker backup file is absent"
}

function post_check_docker(){
  echo -e "\nDocker"

  # Variables that use some helper functions
  VLAN_NODE_IP="$(get_ip_of_interface "${CLUSTER_INTERFACE}")"
  ESCAPED_VLAN_NODE_IP=$(escape_ip_for_regex "${VLAN_NODE_IP}")

  check_if_process_exists "docker"
  evaluate_result $? "  docker is running"

  docker_info | grep -q -E "Cluster\sstore:\sconsul:\/\/${ESCAPED_VLAN_NODE_IP}:8500"
  evaluate_result $? "  docker is configured to use consul as key-value store"

  docker_info | grep -q -E "Cluster\sadvertise:\s${ESCAPED_VLAN_NODE_IP}:2375"
  evaluate_result $? "  docker is configured to listen via tcp at port 2375"

  netstat --numeric --listening --programs --tcp --inet | grep 'docker' | grep -q -E "${ESCAPED_VLAN_NODE_IP}:2375"
  evaluate_result $? "  docker listens on ${VLAN_NODE_IP} via tcp at port 2375 (Docker-Engine)"

}

# docker engine
function configure_docker(){
  echo -e "\n\e[34mConfigure Docker\e[0m"

  # create backup of /etc/default/docker config
  if [[ (! -f "/etc/default/docker.cluster-lab-backup") ]]; then
    cp /etc/default/docker /etc/default/docker.cluster-lab-backup
  fi
  VLAN_NODE_IP="$(get_ip_of_interface "${CLUSTER_INTERFACE}")"
  if [[ $(is_node_cluster_leader) == 0 ]]; then
    LEADER_OR_FOLLOWER="leader"
  else
    LEADER_OR_FOLLOWER="follower"
  fi
  echo "DOCKER_OPTS=$(eval "echo ${DOCKER_OPTS}")" > /etc/default/docker

  systemctl restart docker.service
}

function reset_docker(){
  echo -e "\n\e[34mReset Docker\e[0m"

  if [[ -f "/etc/default/docker.cluster-lab-backup" ]]; then
    mv -f /etc/default/docker.cluster-lab-backup /etc/default/docker
    systemctl restart docker.service
  fi
}
