# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", type: "dhcp"

  config.vm.define "leader" do |leader|
    leader.vm.box = "ubuntu/wily64"
    leader.vm.hostname = 'leader'
  end

  config.vm.define "follower1" do |follower1|
    follower1.vm.box = "ubuntu/wily64"
    follower1.vm.hostname = 'follower1'
  end

  config.vm.define "follower2" do |follower2|
    follower2.vm.box = "ubuntu/wily64"
    follower2.vm.hostname = 'follower2'
  end

  config.vm.synced_folder "..", "/cluster-lab-src"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", keep_color: true, path: "setup_cluster_lab.sh"
end
